---
- project:
    templates:
      - publish-stx-docs
      - stx-api-ref-jobs
    check:
      jobs:
        - openstack-tox-linters
        - ptp-notification-tox-py39
        - k8sapp-ptp-notification-tox-py39
        - k8sapp-ptp-notification-tox-pylint
        - k8sapp-ptp-notification-tox-flake8
        - k8sapp-ptp-notification-tox-metadata
    gate:
      jobs:
        - openstack-tox-linters
        - ptp-notification-tox-py39
        - k8sapp-ptp-notification-tox-py39
        - k8sapp-ptp-notification-tox-pylint
        - k8sapp-ptp-notification-tox-flake8
        - k8sapp-ptp-notification-tox-metadata
    post:
      jobs:
        - stx-ptp-notification-armada-app-upload-git-mirror

- job:
    name: ptp-notification-tox-py39
    parent: tox-py39
    description: |
      Run py39 test for ptp-notification
    nodeset: debian-bullseye
    required-projects:
      - starlingx/integ
    files: 
      - notificationservice-base-v2/*

- job:
    name: k8sapp-ptp-notification-tox-py39
    parent: openstack-tox-py39
    description: |
            Run py39 test for ptp_notification_app
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-ptp-notification/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-ptp-notification/k8sapp_ptp_notification/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-ptp-notification-tox-flake8
    parent: tox
    description: |
      Run flake8 test for k8sapp-ptp-notification-tox-pylint
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-ptp-notification/*
    vars:
      tox_envlist: flake8
      tox_extra_args: -c python3-k8sapp-ptp-notification/k8sapp_ptp_notification/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-ptp-notification-tox-pylint
    parent: tox
    description: |
      Run pylint test for k8sapp-ptp-notification-tox-pylint
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    files:
      - python3-k8sapp-ptp-notification/*
    vars:
      tox_envlist: pylint
      tox_extra_args: -c python3-k8sapp-ptp-notification/k8sapp_ptp_notification/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: k8sapp-ptp-notification-tox-metadata
    parent: tox
    description: |
      Run metadata test for k8sapp-ptp-notification-tox-pylint
    nodeset: debian-bullseye
    required-projects:
      - starlingx/config
      - starlingx/fault
      - starlingx/utilities
      - starlingx/root
    vars:
      tox_envlist: metadata
      tox_extra_args: -c python3-k8sapp-ptp-notification/k8sapp_ptp_notification/tox.ini
      tox_constraints_file: '{{ ansible_user_dir }}/src/opendev.org/starlingx/root/build-tools/requirements/debian/upper-constraints.txt'

- job:
    name: stx-ptp-notification-armada-app-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/ptp-notification-armada-app to
      github.com/starlingx/ptp-notification-armada-app
    vars:
      git_mirror_repository: starlingx/ptp-notification-armada-app
    secrets:
      - name: git_mirror_credentials
        secret: stx-ptp-notification-armada-app-github-secret3
        pass-to-parent: true

- secret:
    name: stx-ptp-notification-armada-app-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - Bg2arz0OPyJitMp969XiMrlz5kON1p/ggoUs7XPQWSMVQh6lcF4SWH9THoA61iIsDfCCK
          N+P7Qgf+uiXD4uIY1N5lz4xFbdWFQD5uLvlcNt98e9XXxLhnYy7ZwfuL+VFYkpZ74ZSsV
          ag9xps9YVDaXBR6pi+wNOmdhFl7KtTOu5rfmwo7PXYyQg7k9SngF788LCIgPMH6gYK8Oc
          fkw8O9jTPX4UzLkQTQpCVQV4je5rduCTQEKi2IE6mXVox3ArKmgMZfhElt2SAQqskzJSv
          1QXsVMYS5PIMDA5R3jSRwV+FfwQrmAkFw9Bs+UbqNRLgUQSYxSpXo61NQ+TeQodXNuwgD
          6/1T+mWTNeN7HVcDxaDnYor9GliXt1//2aVZKksxk+BXsyvQiAu1xDDludWT8f3ZRZHKi
          e7a6MXnTv0ARS3jRK6TIwutvf3wCjmRGdAvNZZLkJ4ODsiPdGm8FXhyn/gPI5xOSSrQnq
          It5SwnqoCuHDDMbQLBQ065hxjkE+IWYTU+jIYFFaM7dGNGo/C7pide4y6t3vfw5nErTHL
          pYdwYyjfPMnKTG6Uhc2zvXlqccIhRBWTu0Pfa5lQPwWdCnFW9d1bgSV1e7M/aqoFDQzRF
          bwn975PGw2dllxXgGFf7QmJ/rTIVAESK4l1mpAkGZNn9KNvUf5vmmf9gFTAvjo=
        - bfTh8rHd/VVIU/a8NAvgrSGQPRmvoiZTIxaIJG6wnLPsUzuBMRdpU4wYhysPThsagZw25
          CMDSCXovkWji7ify5H48taOVq/wv/7/drs/H3+ZlNYO0Wx9qu2xsiuhdjSo/3w9XA4mGi
          4HRsG1SMWYreFbHhJ9or6sG1zGC5Ux4k4LbkSVBSJHnoDkD/dSCkafxhokTLNMT5Kjw3d
          Dc7ZI90EtzPn7IRHfR5MgAAdgq7LNtxZACoZQtllpe0qLd5rZEqZ4gh/Fn3Dbqs7oDq/O
          92ykghJg6IiC3yYfdAQeB1tPP4FF1Xc5UM7ssopY+G3mj/xsXcFi7fJ/TgYHOFeM+4EZJ
          iZu/Q5nln/5LQQ+hSRpKv1IgF8z+3DzegFtU7McBr6fmWjo9j/3DWWZ5A5kxenHOKQv8M
          U7JP0/McsCxwpQNiNtb8NfljZPwIJlU1o/5c9h+kNnUDwN7AxryBJWIDTLuIS7sXVBTpM
          sqcd0gLOa9O8sLP0vtIzNcrE6Y3wC3XQ7LM0Wdw2/soxcS8WlzDOodjOXXTz7BIzzqGjT
          Y/+9aW/2yREgM0+dGtA3Gbwq7cpKIhlZMPby7dYHwwmL3cep/5oGsguocGzUv5hQq9i0j
          jTUUfJPtu0irWA+tnAgLSg6CkzfbwxhxmdiFTI4D8ET/E7PtbVOE4qX1wANfkg=
        - BI1VFRaVcj58ng6WMS2X9phu0K3uRH4qzAVl+0a1ehSzSWINYFvGXNKBrBkMTHc/Tln8z
          l3PQsm0B+t7behfdkJE9gCrUHdxrcUVHxd9pDt4aS+afq7u1Oh7VofmNKRLKNutwuaEy3
          NraHJmJ4CMtqo0AC5JKP7Wt68s1PzCveXdyLCqZhszWUgwIkkWcTPvnx9uxlmRas2PmJu
          hOJ1JXx8zbbw9fSAnJscYmNPdWlgi2+1MxtaknKkY3jYlPLVTKa29kaMTczGi7/UWDXd8
          H4j21Uj/pKhRj0ZQgvzbAkJiuyRnN4NSHYE7B7oUUi1J59e7ZZrR7Jepj7P0X4bz7L4W/
          ObUw0g+eMm5ZNK+qqCVLwVkme7XnvhOaVJe43h5yIR743ouWN7JyVtuLUODS/fDir2Q56
          p2AmnMwQHDm9CJ9XZo6pNSxz8SHPtyyQkKfK+eskmuL+cauFv1X13w077/3SMFq5RUcIZ
          Eg2lM/8jishgUYNpykaK/RQftHJ89g0BGdHuwPcnlMaC+VhnapTy8bcZKblsbnxJeonNw
          jjLCICTUkdu1FgT2SYD12fdCix7QbhYlNmSQu73jFDXEIbyAzLl0XtuGnzFRkLmEwYNMW
          PgkjPlpji2b3VzfaEKLa44kb7M1R+ZKozhjhDX5Nh7o/Ak1brm91l1UPu9m2ko=
        - G7j71CLqE/ujt/JNXiX5+T3TN1ILRpiax1axOIcVE/90C7175Zt4/yirP+5O1ABmnJJQh
          duayvxZSW7XuUKMjLQIQ0D/t74sWn9ZyA5g8/JZ8mE+gqxuQ5OMW1JAx9GTk7A6yQhHx6
          vfK5XL1vJ/LdDS9g4C/u3GjHaNV/fwY3vMjDfN0IQQ1K6sjE2bWSDQADGCl5LHDsliWh/
          vtJzfz+YwHLOEF+8tPC8BU3hpOouEUu4y7qdvevJZHwUmQO9Apa3yJPC2DiEhKrPgTIUL
          axFhTxJa52kJeWA68qwXnhkW9dwr3eARg2QhW0H8FXm1vzKEr61eSUYBx78gepkxFif8j
          7dCQ5xpqaC+t+JEkBv+qG7T+G7WP7lpTBviqjF3y8HVkW2JVtKo+e4JAH6sucdsoegkx8
          QVRyiXkuI+Qs/k9N8Y7J/lsQQMTDq9Q9JsBcOHUOYLAmK6wFNqjXiT1GRANdUbFzgzK2a
          m8T8GQOuhltP54ufCmdJCRC1nFU7p8Pg2GBSlve9d3waHdEv0gwBCNeFQN6+8I5w72Wcp
          R/YjGAR+nqF5rPEpqt6EkP8DpXjh21cYPemYX0TD2LYT5pMaHPUsz7PI27isqmyPwPJjl
          qy80aD7F/NYfuXMQsRdjoI5bvGBR++i8jdCSf2UiSBp59CvOjCAoqirQmVSHXc=
        - oQXAaXmbkr1mpJ5KUPi7M6XjI9N2crHTMeMv3xEmbHv0Bqr3vYJsF6Ggcj4OKeF1hc8e2
          CbZcULskU7hdANcgmoadtuR/p+N4I5tsYPU1zcfFvJBXAvlcLhFXPL9VtW6pWrzG//bzr
          TkRpt97SL48tto4plLBcguvUp3dzg8ANSvalH4OKDAyIBT+5w82TnHWVFB1LihsyNtzOr
          iWx6olV0qIDJ2EX4uc0xkj4ZFVr8Aqi2RQspM8Bsfbud+BLr+ThIq2VRtIK8etMP1aODg
          ohjI/Yx0E/dzJ+YkNTJPhfA/AWd/KyoDl4gEUvjVNUs31mAFonvPAACir9QqWrwSxzo0Q
          blyHilcWMFbTba4d8fI22IpzlDA6vNv0n1suu8CKLDCxX7Nh+mNtPCh/pUtv/x00dB/0A
          uRO0cJeKWYdwkO0DMmRKc8QnsWY5wjhKpgE3lHt+u1ojHJ3MG71aCgKvqTXlM0q885Cub
          lF8Iv5Bbx0HDYMGxcHcN+ZJQN1OK/tw0vimRf7nHCpr8qYpGoxIiZz46WSEIgLlwrbINz
          a6z7KtsuWrZp0G0vU2FJ6SDOTdFDkVH6kb9APN/qCddZAIgQroynihVVUhASBkWVITDev
          oL/WBsmzzs8UqOpvH/CXM3jrHHRzUcMDtgCLqzHGc+bUamnQAXMGyvY0UpsFbY=
        - rbqvROxwkdM++5Tgul03Yd8ExXTRNqpZFmOUy0jXk4BAZRed2/Mq3CFQ9ggbrfeonIcdM
          xWdT0gfCv+r3CfXOE57qS1k7iTxPdOByLSVlH2XQY82X0ELAI5hZALgtzTa3mHzj4uRzi
          FvjYcDLUhvejw43gRQSdK72mHTAIy5bLISandMYpt3PSi0C5I/IJrylKBCeQJmItznLbP
          v5TwyKrrMvS5qKApGX1DnqDRJHarmzwk2ZUiTVtoXYKRz6tPukZf8GiQbfa8BrTdO3cmQ
          0SGsjaQ7y4rImtEW1iNvLi97Q1Ge3x+ypWJKe2U4tkZnD0dCg+5wNLrWLo62qvba+0pTb
          C0ICfnoc7epXB57GNaODsW5QLoe1cyzzOBTo/zCQ1am/w1PMR9bTSlu5jxxS4pJRN/z0f
          ItM9lEzh1DVg0RLoUXwuXczEgJZxRjgTEBTSFIQqEgmvz1itfD8N8FHc8SRUI2URGEsYI
          S6F0n7XCxcW5RCwXGIloTdVemWWzz0AyWUx7ap3V/a/entqrRAr5L1hkc33JUPXPpHtq+
          GBNyewRPHwx8cp1df3gdLtTMftOlyh3R7MTObw+rW53l9Umwk1HULxyws1GEMA8qFeGt8
          zxSz7zMwep/Y9YgID+Qt12EPbd4wrXrl9yTRlmbeUU3JvVyF7/JteBrcV6Lcs4=
        - YHuXFxv8fsQ+kBGmxL7DYuitWAUj6Yjic07VYb43WYxa/LM3xc6LyLx8L2ZZH8L8xqbGT
          OEF58yAk2usmb4/8oJVM2w4Lf1Ghx9pJCE9pWENPUeaBp9RFaYVxKsSTCU/98bPBT2Urc
          T5SpBQInd+kl/rM2A/LauqElIfD+GeoVapnIa1THLDY/tUZPTjavwGTYM/ombx7Kv+N3E
          yaRLp598AO5joXnF7RtN8UUV/A3kAgmDRMb+2XnkIt5NT0AlFqBCwoVgG9pIVm4gCPq5u
          KQ62UpdJ6H0LBDYI1E58vt1Tq8NbEH0SvNm/+nwUSUGV2VwM4WZmGvMGk+Jb0ZJVE+D24
          gBPiH9/LlEThFvNebRcH3cXQU8/tMmobHJrdWdvx2WqgRBu/4ZoSfmkFK1iiTVwKNn3jf
          9jbRELj+EsygSc2GxTBUV83Xt0acyv3bxlFXVu/6dFehB1LVNtQQaBGALPo2mcV479qjl
          oi2+cvFPwa0Vp3f6lyCRNKBNdBELiBSJu1Org1bJ9JtYNqUvXy95P25HiTBQo2lSX36lA
          TDxXpb18Iss/yVy2M5Y++FKQBGecdUwJEnE0FInhFklmCu0gfxiSrjl7ZtaPe9Q6XA/AI
          f8ofhwdelFh4W6huxIaCIb/TGbfWzyqpLXunZg6fVczRNI+gyx3iseCLkqR8Co=
