#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: ptp-notification
  labels:
    chart_group: ptp-notification
spec:
  releaseName: ptp-ptp-notification
  chart:
    spec:
      chart: ptp-notification
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: stx-platform
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: ptp-notification-static-overrides
      valuesKey: ptp-notification-static-overrides.yaml
    - kind: Secret
      name: ptp-notification-system-overrides
      valuesKey: ptp-notification-system-overrides.yaml
