#
# Copyright (c) 2021-2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# Default values for notification services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# global vars for parent and subcharts.
# registration.endpoint.host: registration.{namespace}.svc.{cluster-domain}

replicaCount: 1

nameOverride: ""
fullnameOverride: ""

global:
  namespace: notification

labels:
  isApplication: false

registration:
  imagePullSecrets: default-registry-key
  image:
    repository: rabbitmq
    tag: 3.12.8-management
    pullPolicy: IfNotPresent
  endpoint:
    host: "registration.notification.svc.cluster.local"
    port: 5672
    user: admin
    pass: admin
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: ptp-registration
            operator: In
            values:
            - "true"

notification:
  image:
    repository: rabbitmq
    tag: 3.12.8-management
  endpoint:
    port: 5672
    user: admin
    pass: admin
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: ptp-notification
            operator: In
            values:
            - "true"

location:
  log_level: INFO
  endpoint:
    port: 8080
    liveness: False
  image:
    repository: starlingx/locationservice-base
    tag: stx.10.0-v2.2.1
    pullPolicy: IfNotPresent

ptptracking:
  enabled: True
  imagePullSecrets: default-registry-key
  ptp4lSocket: /var/run/ptp4l-ptp4l-legacy
  ptp4lServiceName: ptp4l-legacy
  ptp4lClockClassLockedList: "6,7,135"
  phc2sysServiceName: phc2sys-legacy
  phc2sysComSocket: False
  logging_level: INFO
  endpoint:
    port: 8081
    liveness: False
  image:
    repository: starlingx/notificationservice-base
    tag: stx.10.0-v2.2.1
    pullPolicy: IfNotPresent
  device:
    simulated: false
    holdover_seconds: 15
    poll_freq_seconds: 2

ptptrackingv2:
  enabled: True
  imagePullSecrets: default-registry-key
  ptp4lSocket: /var/run/ptp4l-ptp4l-legacy
  ptp4lServiceName: True
  ptp4lClockClassLockedList: "6,7,135"
  phc2sysServiceName: True
  phc2sysToleranceThreshold: 1000
  ts2phcServiceName: True
  log_level: INFO
  endpoint:
    port: 8082
    liveness: False
  image:
    repository: starlingx/notificationservice-base-v2
    tag: stx.10.0-v2.2.1
    pullPolicy: IfNotPresent
  control_timeout: 2
  device:
    simulated: false
    holdover_seconds: 15
  osclock:
    holdover_seconds: 15
  overall:
    holdover_seconds: 15

