#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# HelmRepository YAML for Starlingx helm repository.
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stx-platform
spec:
  url: http://192.168.206.1:8080/helm_charts/stx-platform
  interval: 1m  # interval to check the repository for updates
