#
# Copyright (c) 2021 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registration
  namespace: {{ .Values.global.namespace }}
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        app.starlingx.io/component: {{ ternary "application" "platform" .Values.labels.isApplication}}
      annotations: {
        configchecksum: {{ toYaml .Values.labels | sha256sum | trunc 63 }}
      }
    spec:
      imagePullSecrets:
      - name: {{ .Values.registration.imagePullSecrets }}
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
{{- if .Values.registration.affinity }}
      affinity:
{{ toYaml .Values.registration.affinity | indent 8 }}
{{- end }}
      containers:
      - name: rabbitmq
        image: "{{ .Values.registration.image.repository }}:{{ .Values.registration.image.tag }}"
        env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "admin"
            - name: RABBITMQ_DEFAULT_PORT
              value: "5672"
---
