#
# Copyright (c) 2021 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: v1
kind: Service
metadata:
  name: registration
  namespace: {{ .Values.global.namespace }}
spec:
  #clusterIP: None
  ports:
  - name: rabbitmq
    port: 5672
    protocol: TCP
  selector:
    app: rabbitmq